//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OtelEleven.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlangıç Tarihi.
        /// </summary>
        public static string Baslangic {
            get {
                return ResourceManager.GetString("Baslangic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitiş Tarihi.
        /// </summary>
        public static string Bitis {
            get {
                return ResourceManager.GetString("Bitis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş Odalar.
        /// </summary>
        public static string Bos {
            get {
                return ResourceManager.GetString("Bos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boş Oda Kalmadı .
        /// </summary>
        public static string Bosoda {
            get {
                return ResourceManager.GetString("Bosoda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Tarihi.
        /// </summary>
        public static string Cikis {
            get {
                return ResourceManager.GetString("Cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string Detaylar {
            get {
                return ResourceManager.GetString("Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etkinlikler.
        /// </summary>
        public static string Etkinlikler {
            get {
                return ResourceManager.GetString("Etkinlikler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Tarihi.
        /// </summary>
        public static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string GirişYap {
            get {
                return ResourceManager.GetString("GirişYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkımızda {
            get {
                return ResourceManager.GetString("Hakkımızda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İndirim.
        /// </summary>
        public static string İndirim {
            get {
                return ResourceManager.GetString("İndirim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kampanyalar.
        /// </summary>
        public static string Kampanyalar {
            get {
                return ResourceManager.GetString("Kampanyalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katılımlarınızı Bekliyoruz....
        /// </summary>
        public static string Katılm {
            get {
                return ResourceManager.GetString("Katılm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odalar.
        /// </summary>
        public static string Odalar {
            get {
                return ResourceManager.GetString("Odalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Seçiniz.
        /// </summary>
        public static string OdaSeç {
            get {
                return ResourceManager.GetString("OdaSeç", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnci Otel Büyük Etkinlikleri.
        /// </summary>
        public static string OtelEtk {
            get {
                return ResourceManager.GetString("OtelEtk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon Yap.
        /// </summary>
        public static string Rez {
            get {
                return ResourceManager.GetString("Rez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon.
        /// </summary>
        public static string Rezervasyon {
            get {
                return ResourceManager.GetString("Rezervasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Numarasını Seçiniz.
        /// </summary>
        public static string SEC {
            get {
                return ResourceManager.GetString("SEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçenekler.
        /// </summary>
        public static string Secenekler {
            get {
                return ResourceManager.GetString("Secenekler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son 5 Üye Yorumları.
        /// </summary>
        public static string Son {
            get {
                return ResourceManager.GetString("Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Haklar Saklıdır.
        /// </summary>
        public static string TümHaklar {
            get {
                return ResourceManager.GetString("TümHaklar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye ol.
        /// </summary>
        public static string UyeOl {
            get {
                return ResourceManager.GetString("UyeOl", resourceCulture);
            }
        }
    }
}
